---
deployment:
  tasks:
    - export DEPLOYPATH=/home/YOUR_CPANEL_USERNAME/public_html/hr/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R index.html api database.sql setup_admin.php .htaccess README.txt $DEPLOYPATH
